version: 2.1

jobs:
  build:
    docker:
      # Utilise une image CircleCI contenant Node.js
      - image: cimg/node:16.20
    steps:
      # Étape 1 : Récupération du code source
      - checkout

      # Étape 2 : Configurer Docker distant
      - setup_remote_docker

      # Étape 3 : Construire l'image Docker
      - run:
          name: Build Docker image
          command: docker build -t node-js-sample .

      # Étape 4 : Tester le conteneur Docker
      - run:
          name: Test Docker container
          command: |
            # Lancer le conteneur et définir le port
            docker run -d -p 8080:8080 --name test-container -e PORT=8080 node-js-sample
            
            # Attendre le démarrage
            sleep 10

            # Afficher les logs du conteneur
            docker logs test-container

            # Vérifier si l'application répond sur 8080
            curl -v http://127.0.0.1:8080 || (echo "App failed to start" && exit 1)

      # Étape 5 : Pousser l'image sur DockerHub
      - run:
          name: Push to DockerHub
          command: |
            # Connexion à DockerHub
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            
            # Tag de l'image
            docker tag node-js-sample:latest $DOCKER_USERNAME/node-js-sample:latest
            
            # Pousser l'image vers DockerHub
            docker push $DOCKER_USERNAME/node-js-sample:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
