version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.20
    steps:
      # Étape 1 : Vérifier le code source
      - checkout

      # Étape 2 : Configurer Docker distant
      - setup_remote_docker

      # Étape 3 : Construire l'image Docker
      - run:
          name: Build Docker image
          command: docker build -t node-js-sample .

      # Étape 4 : Tester le conteneur Docker
      - run:
          name: Test Docker container
          command: |
            # Lancer le conteneur avec le port et les variables d'environnement
            docker run -d -p 8080:8080 --name test-container -e PORT=8080 node-js-sample
            
            # Attendre que le conteneur démarre
            sleep 5
            
            # Afficher les logs pour déboguer en cas de problème
            docker logs test-container
            
            # Tester si le conteneur répond sur le port 8080
            curl -v http://127.0.0.1:8080 || (echo "App failed to start" && exit 1)

      # Étape 5 : Pousser l'image Docker sur DockerHub
      - run:
          name: Push to DockerHub
          command: |
            # Se connecter à DockerHub
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            
            # Ajouter un tag à l'image Docker
            docker tag node-js-sample:latest $DOCKER_USERNAME/node-js-sample:latest
            
            # Pousser l'image vers DockerHub
            docker push $DOCKER_USERNAME/node-js-sample:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
