version: 2.1

jobs:
  build:
    machine:
      # Utilisation d'une machine Ubuntu 20.04
      image: ubuntu-2004:202004-01
    steps:
      # Étape 1 : Vérifier le code source
      - checkout

      # Étape 2 : Construire l'image Docker
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker

      - run:
          name: Build Docker image
          command: docker build -t node-js-sample .

      # Étape 3 : Tester le conteneur Docker
      - run:
          name: Test Docker container
          command: |
            docker run -d -p 8080:8080 --name test-container -e PORT=8080 node-js-sample
            echo "Waiting for the container to start..."
            sleep 10
            docker logs test-container
            curl -v http://127.0.0.1:8080 || (echo "App failed to start" && exit 1)

      # Étape 4 : Pousser l'image Docker sur DockerHub
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag node-js-sample:latest $DOCKER_USERNAME/node-js-sample:latest
            docker push $DOCKER_USERNAME/node-js-sample:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
