version: 2.1

jobs:
  build:
    machine: true  # Utilise la machine CircleCI par défaut (Ubuntu)
    steps:
      # 1. Récupérer le code source
      - checkout

      # 2. (Optionnel) Vérifier la version de Docker
      - run:
          name: Check Docker version
          command: |
            docker --version
            docker ps || true

      # 3. (Optionnel) Démarrer Docker si nécessaire
      - run:
          name: Start Docker
          command: |
            sudo service docker start
            docker info

      # 4. Construire l'image Docker (à partir du Dockerfile dans le repo)
      - run:
          name: Build Docker image
          command: docker build -t node-js-sample .

      # 5. Tester l'application dans le conteneur
      - run:
          name: Test Docker container
          command: |
            docker run -d -p 8080:8080 --name test-container -e PORT=8080 node-js-sample
            echo "Waiting for the container to start..."
            sleep 10
            docker logs test-container
            curl -v http://127.0.0.1:8080 || (echo "App failed to start" && exit 1)

      # 6. Pousser l'image sur DockerHub
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag node-js-sample:latest $DOCKER_USERNAME/node-js-sample:latest
            docker push $DOCKER_USERNAME/node-js-sample:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
