version: 2.1

jobs:
  build:
    machine: true
    steps:
      # 1. Récupérer le code source
      - checkout

      # 2. Supprimer d’éventuelles anciennes versions de Docker/containerd
      - run:
          name: Remove conflicting packages
          command: |
            sudo apt-get remove -y containerd docker docker-engine docker.io runc || true
            sudo apt-get update

      # 3. Préparer l'installation de Docker
      - run:
          name: Prepare system for Docker install
          command: |
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
            sudo apt-get update

      # 4. Installer Docker CE et containerd.io
      - run:
          name: Install Docker
          command: |
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      # 5. Construire l'image Docker
      - run:
          name: Build Docker image
          command: docker build -t node-js-sample .

      # 6. Tester l'application dans le conteneur
      - run:
          name: Test Docker container
          command: |
            docker run -d -p 8080:8080 --name test-container -e PORT=8080 node-js-sample
            echo "Waiting for the container to start..."
            sleep 10
            docker logs test-container
            curl -v http://127.0.0.1:8080 || (echo "App failed to start" && exit 1)

      # 7. Pousser l'image sur DockerHub
      - run:
          name: Push to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag node-js-sample:latest $DOCKER_USERNAME/node-js-sample:latest
            docker push $DOCKER_USERNAME/node-js-sample:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
